# 捕获异常

在 Java 中，凡是可能抛出异常的语句，都可以使用 `try{} catch{}` 捕获。



## 多catch语句

可以使用多个 `catch`语句，每个 `catch` 语句分别捕获对应的 `Exception` 及其子类。

JVM在捕获到异常后，会从上到下匹配 `catch` 语句，匹配到某个 `catch` 后，执行 `catch` 代码块，然后不再继续匹配。

::: warning 注意

1. 存在多个 `catch` 的时候，`catch`的顺序非常重要，子类必须写在前面！

:::

```java {4,6}
public static void main(String[] args) {
  try {
    Process1();
  } catch (UnsupportedEncodingException e) {
    System.out.println("Bad Encoding");
  } catch (IOException e) {
    System.out.println("IO Exception");
  }
}
```

上面代码中 `UnsupportedEncodingException` 是 `IOException` 的子类，因此 `UnsupportedEncodingException`在前，`IOException`在后。



## finally语句

`finally` 语句用于 不论是否有异常发生，`finally` 中的代码都会执行。

```java {8-10}
public static void main(String[] args) {
  try {
    Process1();
  } catch (UnsupportedEncodingException e) {
    System.out.println("Bad Encoding");
  } catch (IOException e) {
    System.out.println("IO Exception");
  } finally {
    System.out.println("completed!");
  }
}
```

在某些情况下，可以没有 `catch`，只是用 `try{} finally{}` 结构：

```java
try {
  System.out.println("hello");
} finally {
  System.out.println("world");
}
```



## 异常合并

如果某些异常的处理逻辑相同，但是异常本身不存在继承关系，那么可以将异常进行合并处理。

```java {3}
try {
  Process1();
} catch (IOException | NumberFormatException e) {
  System.out.println("Bad input");
} catch (Exception e) {
  System.out.println("Unknown error");
}
```